### ISSUE TITLE
New pilot_reconstructions Error

### ISSUE THREAD

**Issue by myahcaplan** [alec-hoyland/tinnitus-reconstruction#190]
I tried running the pilot_reconstructions script and got the following error. It was working on the same dataset last term, so I'm not sure why it isn't working now

![Issue](https://user-images.githubusercontent.com/25419912/213512504-2023d94c-775a-47be-980c-f1e0aacbc44a.JPG)

**Comment by nelson-barnett** [comment]
Try setting `n_trials = inf` in line 106 of `pilot_reconstructions.m`. That variable sets the number of trials to use from each config in the data set. It really should be set to `inf` in main -- that was an oversight. So, if that works feel free to submit a PR with the change or lmk and I can do it. It might be that one of the configs you have in the data directory has less than 200 trials that is causing the error.

**Comment by myahcaplan** [comment]
I made the change and nothing changed; it's giving the same error message

**Comment by nelson-barnett** [comment]
Does it work for you on the data from the paper ("data-paper-8-bins" in OneDrive)? I'm not getting any errors when I run that. Also, is the error on one particular person's data or does it happen on everyone's? It seems to imply that there is no data in `stimuli_matrix` for the particular subject, but there should be an earlier (and clearer) error if there's no stimuli files at all.
