### ISSUE TITLE
Gaussian stdev vs var in gen stim

### ISSUE THREAD

**Issue by nelson-barnett** [alec-hoyland/tinnitus-reconstruction#207]
I noticed this when comparing my Julia version to the matlab output. I think these lines should be `sqrt(self.amplitude_var)` and `sqrt(self.n_bins_filled_var)`. Would you agree? I want to make sure I'm understanding it correctly when doing the conversion. 

https://github.com/alec-hoyland/tinnitus-reconstruction/blob/c08fec68cdb3b26f198aa95565b07106113f5e37/code/stimulus_generation/%40GaussianNoiseStimulusGeneration/generate_stimulus.m#L45

https://github.com/alec-hoyland/tinnitus-reconstruction/blob/c08fec68cdb3b26f198aa95565b07106113f5e37/code/stimulus_generation/%40GaussianPriorStimulusGeneration/generate_stimulus.m#L60

**Comment by alec-hoyland** [comment]
Yes there should be a `sqrt` there. I tend to be unsafely lax with the difference between standard deviation and variance...
