### ISSUE TITLE
Power spectra first col

### ISSUE THREAD

**Issue by nelson-barnett** [alec-hoyland/tinnitus-reconstruction#210]
It looks like the first column is always zeros here. Is that correct? I would think it should be filled with the `10*log10(pxx)` of the first audio file.

https://github.com/alec-hoyland/tinnitus-reconstruction/blob/e493006a46ba55485c92c17d2c392a4f51f05bb5/code/stimulus_generation/%40PowerDistributionStimulusGeneration/build_distribution.m#L49

**Comment by alec-hoyland** [comment]
You're right. The pxx variable from the line above should be filled in there. The reason it's done this way is so you can get the size of the matrix based on the length of pxx.
